# Generated by Django 5.1.7 on 2025-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic.png', upload_to='profile_pic'),
        ),
    ]
